# Generated by Django 2.2 on 2019-06-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190601_1507'),
        ('main_app', '0013_auto_20190605_1804')
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Recipe'),
        ),
    ]
