# Generated by Django 2.2 on 2019-06-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190605_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useringredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='useringredient',
            name='user',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='dish',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='user',
            name='ingredients',
            field=models.ManyToManyField(to='main_app.Ingredient'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='tools',
            field=models.ManyToManyField(to='main_app.CookingTool'),
        ),
        migrations.AddField(
            model_name='user',
            name='tools',
            field=models.ManyToManyField(to='main_app.CookingTool'),
        ),
        migrations.DeleteModel(
            name='UserCookingTool',
        ),
        migrations.DeleteModel(
            name='UserIngredient',
        ),
    ]
