# Generated by Django 2.2 on 2019-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190522_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
