# Generated by Django 2.2 on 2019-06-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190522_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DishDetails',
            new_name='DishIngredient',
        ),
    ]
