# Generated by Django 2.2 on 2019-06-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190601_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.ManyToManyField(through='main_app.IngredientUnit', to='main_app.Unit'),
        ),
    ]
