# Generated by Django 2.2 on 2019-06-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190601_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishingredient',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Unit'),
        ),
    ]
