# Generated by Django 2.2 on 2019-06-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_dishingredient_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='DishCookingTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Dish')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.CookingTool')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='tools',
            field=models.ManyToManyField(through='main_app.DishCookingTool', to='main_app.CookingTool'),
        ),
    ]
