# Generated by Django 2.2 on 2019-06-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190601_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
