# Generated by Django 2.2 on 2019-06-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_dish_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
