# Generated by Django 2.2 on 2019-06-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_dish_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientunit',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientunit',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='units',
        ),
        migrations.AddField(
            model_name='dish',
            name='tools',
            field=models.ManyToManyField(to='main_app.CookingTool'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.ManyToManyField(to='main_app.Unit'),
        ),
        migrations.DeleteModel(
            name='DishCookingTool',
        ),
        migrations.DeleteModel(
            name='IngredientUnit',
        ),
    ]
