# Generated by Django 2.2 on 2019-06-05 16:04

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20190605_1804'),
        ('accounts', '0003_auto_20190605_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishingredient',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='dishingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='dishingredient',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='DishIngredient',
        )
    ]
