# Generated by Django 2.2 on 2019-06-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_dish_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.ManyToManyField(blank=True, to='main_app.Unit'),
        ),
    ]
