# Generated by Django 2.2 on 2019-06-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20190606_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='times_rated',
            field=models.IntegerField(default=0),
        ),
    ]
