# Generated by Django 2.2 on 2019-06-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20190609_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='average_rating',
            new_name='sum_rating',
        ),
    ]
